NO JIRA ISSUE
DANS-KNAW/easy-stage-dataset pull request #107
Opened 2017-03-22 10:53 UTC by janvanmansum

During the test run with Mendeley license URIs were sent that were almost correct, but
used https instead of http. Made the selection of the license file more liberal so that
https instead of http is accepted, and one redundant trailing space is ignored.

@DANS-KNAW/easy

2017-03-22 11:15 UTC, rvanheest requested changes

2017-03-22 11:15 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/stage/dataset/AdditionalLicense.scala
> +
whitespace?

2017-03-22 11:15 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/stage/dataset/AdditionalLicense.scala
> +    val httpUri = {
why in a code block?

2017-03-22 11:15 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/stage/dataset/AdditionalLicense.scala
> +      if (uri.getScheme == "https") new URI("http", uri.getUserInfo, uri.getHost, uri.getPort, uri.getPath, uri.getQuery, uri.getFragment)
maybe a bit hard to see, but this only changes a `https` scheme to a `http` scheme, right?
Maybe you should put this in a separate method (for example `withScheme(uri: URI, scheme: String): URI`) to make it more clear what you're doing.

2017-03-22 11:15 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/stage/dataset/AdditionalLicense.scala
> +    licenses.get(httpUri.toASCIIString).orElse {
Not sure, but there is a method in the `Map` API called `getOrElse`. Can't you use that one here? (haven't tried, just asking)

2017-03-22 11:15 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/stage/dataset/AdditionalLicense.scala
> +   * - https is excepted instead of http
shouldn't this be reversed?

2017-03-22 11:15 UTC, rvanheest commented on src/main/scala/nl/knaw/dans/easy/stage/dataset/AdditionalLicense.scala
> +   * @return
specify what it returns:
* when does the user receive a `Some`
* when does the user receive a `None`
* is the file relative or absolute

2017-03-23 12:24 UTC, janvanmansum commented on src/main/scala/nl/knaw/dans/easy/stage/dataset/AdditionalLicense.scala
> +    licenses.get(httpUri.toASCIIString).orElse {
I can't use that here, because I want to return an `Option` not the unwrapped `File` object.

2017-03-23 12:28 UTC, rvanheest approved these changes
LGTM

2017-03-23 13:00 UTC, merged