Differentiation of REJECTED and FAILED deposit state
DANS-KNAW/easy-stage-dataset pull request #97
Opened 2016-11-16 14:20 UTC by vesaakerman

fixes EASY-1146

When applied it will

* throw `RejectedDepositException` when deposit state should be set to **REJECTED**
* give in `RejectedDepositException` the message that will be relayed to the client

#### related pull requests on github
repo                       | PR
-------------------------- | -----------------
easy-ingest-dispatcher	     |  [41]
easy-ingest-flow    	     |  [61]

2016-11-16 16:06 UTC, janvanmansum commented on src/main/scala/nl/knaw/dans/easy/stage/package.scala
> +  // exceptions
Unnecessary comment. After all, the thing is called a `RejectedDeposit`**`Exception`**.

2016-11-16 16:08 UTC, janvanmansum commented on src/main/scala/nl/knaw/dans/easy/stage/package.scala
> +  case class RejectedDepositException(msg: String = "", cause: Throwable = null) extends Exception(msg, cause)
* I think we should not have a default empty message. You should always report something back to the client.
* Not sure if we would use the `Throwable` at all. From today's discussion I understood the idea was to log everything right way and not propagate all the details upstairs.

2016-11-16 16:27 UTC, janvanmansum commented on src/main/scala/nl/knaw/dans/easy/stage/dataset/Util.scala
> +      error(s"Unable to find `$fileName` in bag.")
Good idea to use standard functions! 👍

2016-11-16 16:34 UTC, janvanmansum requested changes
Almost ready for merge. Can be improve a bit; see my comments.

2016-11-16 16:34 UTC, janvanmansum requested changes
Almost ready for merging.

2016-11-17 07:22 UTC, vesaakerman commented on src/main/scala/nl/knaw/dans/easy/stage/package.scala
> +  case class RejectedDepositException(msg: String = "", cause: Throwable = null) extends Exception(msg, cause)
The idea of logging the error right away was in combination of using Either in place of Try.  Now the idea is indeed to propagate also the details upstairs, and do logging in one central place.

2016-11-17 09:19 UTC, rvanheest approved these changes
Looks good to me!

2016-11-18 13:29 UTC, merged